name: fz_courier
description: A new Flutter application.

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  grouped_buttons: ^1.0.4
  flutter_phoenix: ^0.1.0
  flutter_xlider: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_rename_app: ^1.0.0

flutter_rename_app:
  application_name: Fz Courier
  dart_package_name: fz_courier
  application_id: com.fz.courier
  bundle_id: com.fz.courier
  android_package_name: com.fz.courier

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Bold.ttf
        - asset: fonts/ProductSans-Regular.ttf

